# -*- coding: utf-8 -*-
"""denoising

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dVCFOnjc6WT9ay3LRoPjdq6MArKDGZiy
"""

!import numpy as np
!import soundfile as sf
!import noisereduce as nr
!import librosa
from scipy import signal

noisy_audio, sr = librosa.load('noisy_speech.wav', sr=None)

noise_clip = noisy_audio[:50000]
noise_std = np.std(noise_clip)

reduced_audio = nr.reduce_noise(audio_clip=noisy_audio, noise_clip=noise_clip, verbose=False)

sf.write('enhanced_audio.wav', reduced_audio, sr)